### ISSUE TITLE
Improvement on background text selection in nightly verison.

### ISSUE THREAD

**Issue by Username-Username007** [xournalpp/xournalpp.github.io#84] opened 2023-04-22 03:32 UTC
Currently, I can set the right mouse button to use "Select Linear PDF Text" tool, and then highlight it.
The problem is, this tool itself has a "color property" that I can decide to highlight the selected text but when I released the right mouse button, the tool just changed to the previous tool before I pressed the right mouse button. So, the color is not the one I set for the text highlighter, but the color of the previous tool.
![image](https://user-images.githubusercontent.com/77972359/233759895-bbed24f5-af06-4d13-8073-d645c483d05f.png)

My suggestion is keep the "Select Text" tool alive until the popped up dialog
![image](https://user-images.githubusercontent.com/77972359/233759910-07d1852a-da47-45bc-ac27-9a104189869d.png)
is destroyed so that I can use the highlighter's color.

**Comment by Technius** [comment] 2023-04-23 20:40
Duplicate of https://github.com/xournalpp/xournalpp/issues/4819

**Closed by Technius** 2023-04-23 20:40 UTC
